### ISSUE TITLE
Missing tenant id for Azure

### ISSUE THREAD

**Issue by juliancheal** [juliancheal/ManageIQ-Cli#10]
When creating an Azure provider, the provider is missing the `tenant id`.

**Comment by snecklifter** [comment]
@juliancheal I'm hitting this too when trying to add Azure as an Ansible Provider here:

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/manageiq/manageiq_provider.py

**Comment by juliancheal** [comment]
This seems to be the reason https://github.com/ManageIQ/manageiq-providers-azure/issues/197

**Comment by juliancheal** [comment]
Fixed
